# Промисы, `async`, `await`

# 2. Промисы
- Функция, переданная в конструктор `new Promise`, называется исполнитель (`executor`).
- Её аргументы - `resolve` и `reject` - это колбеки, которые предоставляет сам `JS`.
- Итак, исполнитель запускается автоматически, он должен выполнить работу, а затем вызвать `reolve` или `reject`.
- У объекта `promise` есть внутренние свойства:
    - `state`:
        - Вначале `pending`, потом меняется на `fulfilled` при вызове `resolve` или на  `rejected` при вызове`reject`.
    - `result`:
        - Вначале `undefined`, далее изменяется на `value` при вызове `resolve(value)` или на `error` при вызове `reject(error)`.
- Только одно, либо `resolve`, либо `reject`.
- Вызывайте `reject` с объектом `Error`.
- Свойства `state` и `result` - внутренние:
    - Мы не имеем к ним прямого доступа.
    - Для обработки результата следует использовать методы `.then/.catch/.finally`.
- `then`:
    - `Первый аргумент` - функция, которая выполняется, когда промис переходит в состояние выполнен успешно, и получает результат.
    - `Второй аргумент` - функция, которая выполняется, когда промис переходит в состояние с ошибкой, и получает ошибку.
    - Например:
        ```js
        let promise = new Promise(function(resolve, reject) {
            setTimeout(() => resolve('done!'), 1000)
        })
        prompt.then(
            result => alert(result), // выведет 'done!' через одну секунду
            error => alert(error) // не будет запущена
        )
        ```
    - Выполнится первая, а в случае ошибки выполнится вторая.
- `catch`:
    - Если мы хотели бы только обработать ошибку, то можно использовать `null` в качестве первого аргумента:
        ```js
        .then(null, errorHandlingFunction).
        ```
    - Или можно воспользоваться методом `.catch(errorHandlingFunction)`, сделает то же.
    - Вызов `.catch(f)` - это сокращённый вариант `.then(null, f)`.
- `finally`:
    - Вызов `.finally(f)` похож на `.then(f, f)`, в том смысле, что `f` выполнится в любом случае, когда промис завершится успешно или с ошибкой.
    - `finally` хорошо подходит для очистки, например остановки индикатора загрузки, его ведь нужно остановить вне зависимости от результата.
    - Но это не совсем псевдоним `then(f, f)`, как можно было подумать
    - Отличия:
        1. Обработчик, вызываемый `finally`, не имеет аргументов.
            В `finally` мы не знаем, как был завершён промис.
            И это нормально, потому что обычно наша задача - выполнить общие завершающие процедуры.
        2. Обработчик `finally` пропускает результат или ошибку дальше, к последующим обработчикам.
        3. Вызов `.finally(f)` удобнее, чем `.then(f, f)` - не надо дублировать функции `f`.

## 3. Цепочка промисов
- Можно создавать цепочки промисов с помощью .then после каждого результата.
    ```js
    new Promise(resolve => {
        resolve(1)
    }).then(result => {
        return new Promise(resolve => {
            resolve(2)
        })
    }).then(result => {
        //...
    })
    ```
- `Thenable`:
    - Обработчик может возвращать не именно промис, а любой объект, содержащий метод `.then`, такие объекты называются `thenable`, и этот объект будет обработан как промис.
    - Смысл в том, что сторонние библиотеки могут создавать свои собственные  совместимые с промисами объекты.
    - Они могут иметь свои наборы методови при этом быть совместимыми со встроенными промисами, так как реализуют метод `.then`.

## 4. Промисы - обработка ошибок
- Если промис завершается с ошибкой, то управление переходит в ближайший обработчик ошибок.
- `.catch` не обязательно должен быть сразу после ошибки, он может быть далее, после одного или даже нескольких `.then`.
- Неявный `try..catch`:
    - Вокруг функции промиса и обработчиков находится невидимый `try..catch`.
    - Если происходит исключение, то оно перехватывается, и промис считается отклонённым с этой ошибкой.
    - Например:
        ```js
        new Promise((resolve, reject) => {
            throw new Error('Ошибка!')
        }).catch(alert) // Error: Ошибка!
        ```
    - Работает так же, как и этот:
        ```js
        new Promise((resolve, reject) => {
            reject(new Error('Ошибка!'))
        }).catch(alert) // Error: Ошибка!
        ```
    - Это работает не только в функции промиса, но и в обработчиках.
        ```js
        new Promise((resolve, reject) => {
            resolve('ok')
        }).then(result => {
            throw new Error('Ошибка!')
        }).catch(alert) // Error: Ошибка!
        ```
    - Не только для ошибок, которые вызваны оператором `throw`.
    - Например программная ошибка.
- Пробрасывание ошибок:
    - Мы можем иметь столько обработчикок `.then`, сколько мы хотим, и затем использовать один `.catch` в конце, чтобы перехватить ошибки из всех обработчиков.
    - Если мы пробросим ошибку внутри блока `.catch`, то управлени перейдёт к следующему ближайшему обработчику ошибок.
- Необработанные ошибки:
    - Что, если ошибка не будет обработана?
        ```js
        new Promise(() => {
            noSuchFunction()
        }).then(() => {})
        ```
    - В случае ошибки выполнение должно перейти к ближайшему обработчику ошибок.
    - Но в примере выше нет никакого обработчика.
    - Поэтому ошибка как бы застревает, её некому обработать.
    - Что происходит, когда обычная ошибка не перехвачена `try..catch`?
    - Скрипт умирает с сообщением в консоли.
    - Похожее происходит и в случае необработанной ошибки промиса.

## 5. `Promise API`
- В классе `Promise` есть 5 статических методов.
- `Promise.all`:
    ```js
    let promise = Promise.all([...промисы])
    ```
    - Принимает массив промисов (может принимать любой перебираемый объект) и  возвращает новый промис.
    - Новый промис завершится, когда завершится весь переданный список промисов, и его результат будет массив их результатов.
    - Порядок элементов массива в точности соответствует порядку исходных промисов.
    - Часто применяемый трюк - пропустить массив данных через map-функцию, которая для каждого элементы создаст задачу-промис, и затем обернёт получившийся массив в `Promise.all`.
        ```
        let urls = [
            'https://api.github.com/users/iliakan',
            'https://api.github.com/users/remy',
            'https://api.github.com/users/jeresig'
        ]
        let requests = urls.map(url => fetch(url))
        Promise.all(requests).then(responses => responses.forEach(
            response => alert(`${response.url}: ${response.stastus}`)
        ))
        ```
    - Если любой из промисов завершится с ошибкой, то промис, возвращённый `Promise.all`, немедленно завершается с этой ошибкой.
    - Если промис завершается с ошибкой, то весь `Promise.all` завершается с ней, полностью забывая про остальные промисы в списке.
- `Promise.allSettled`:
    - Новая возможность.
    - Метод `Promise.allSettled` всегда ждёт завершения всех промисов.
    - В массиве результатов будет:
        - `{status: 'fulfilled', value: результат}` для успешных завершений.
        - `{status: 'rejected', reason: ошибка}` для ошибок.
- `Promise.race`:
    - Очень похож на `Promise.all`, но ждёт только первый промис, из которого берёт результат (или ошибку).
        ```js
        let promise = Promise.race(iterable)
        ```
- `Promise.resolve/reject`:
    - Редко используются в современном коде, так как синтаксис `async/await` делает его, в общем-то не нужным.
        - `Promise.resolve(value)` создаёт успешно выполненный промис с результатом `value`.
            То же самое, что:
                ```js
                let promise = new Promise(resolve => resolve(value))
                ```
            Этот метод используется для совместимости, когда ожидается, что функция возвратит именно промис.
        - `Promise.reject`:
            `Promise.reject(error)` создаёт промис, завершенный с ошибкой `error`.
            То же самое, что:
                ```js
                let promise = new Promise((resolve, reject) => reject(error))
                ```
            На практике этот метод почти никогда не используется.

## 6. Промисификация
- `Промисификация` – это длинное слово для простого преобразования.
- Мы берём функцию, которая принимает колбек и меняем её, чтобы она вместо этого возвращала промис.
- Такие преобразования часто необходимы в реальной жизни, так как многие функции и библиотеки основаны на колбеках, а использование промисов более удобно, поэтому есть смысл промисифицировать их.

## 7. Микрозадачи
- Обработчики промисов `.then/.catch/.finally` всегда асинхроны.
- Даже когда промис сразу же выполнен, код в строках ниже будет запущен до этих обработчиков.
    ```js
    let promise = Promise.resolve()
    promise.then(() => alert('промис выполнен'))
    alert('код выполнен') // этот alert показывается первым
    ```
- Очередь микрозадач:
    - Асинхронные задачи требуют правильного управления.
    - Для этого стандарт предусматривает внутреннюю очередь PromiseJobs, более известную как очередь микрозадач (`microtask queue`) (термин `V8`).
    - Как сказано в спецификации:
        - Очередь определяется как первым-пришёл-первым-ушёл (`FIFO`): задачи, попавшие в очередь первыми, выполняются тоже первыми.
        - Выполнение задачи происходит только в том случае, если ничего больше не запущено. Или, проще говоря, когда промис выполнен, его обработчики попадают в очередь.
        - Они пока не выполняются. Движок `JS` берёт задачу из очереди и выполняет её, когда он освободится он выполнения текущего кода.
    - Вот почему сообщение 'код выполнен' в примере выше будет показано первым.
    - Обработчики промисов всегда проходят через эту внутреннюю очередь.
    - Если есть цепочка с несколькими `.then/catch/finally`, то каждый из них выполняется асинхронно. То есть сначала ставится на очередь, а потом выполняется, когда выполнение текущего кода завершено и добавленные ранее в очередь обработчики выполнены.
    - Но что если порядок имеет значение для нас? Как мы можем вывести 'код выполнен' после 'промис выполнен'?
    - Легко, используя `.then`:
        ```js
        Promise.resolve()
            .then(() => alert('промис выполнен!'))
            .then(() => alert('код выполнен'))
        ```
- Необработанные ошибки:
    - Теперь мы можем описать, как именно JS понимает, что ошибка не обработана.
    - Необработанная ошибка возникает в случае, если ошибка промиса не обрабатывается в конце очереди микрозадач.
    - Обычно, если мы ожидаем ошибку, мы добавляем .catch в конец цепочки промисов, чтобы обработать её.
    - Но если мы забудем добавить `.catch`, то, когда очередь микрозадач опустеет, движок сгенерирует событие:
        ```js
        let promise = Promise.reject(new Error('Ошибка в промисе!'))
        window.addEventListener('unhandledrejection', event => alert(event.reason))
        ```
    - А что, если мы помаем ошибку, но позже? Вот так:
        ```js
        let promise = Promise.reject(new Error('Ошибка в промисе!'))
        setTimeout(() => promise.catch(err => alert('поймана'), 1000))
        window.addEventListener('unhandledrejection', event => alert(event.reason))
        ```
    - Теперь при запуске, мы сначала увидим 'Ошибка в промисе!', а затем 'поймана'.
    - Если бы мы не знали про очередь микрозадач, то могли бы удивиться, почему сработал обработчик `unhandledrejection`? Мы же поймали ошибку.
    - Но теперь мы понимаем, что событие `unhandledrejection` возникает, когда очередь микрозадач завершена: движок проверяет все промисы и, если какой-либо из них в состоянии `rejected`, то генерируется это событие.
    - В примере выше `.catch`, добавленный в `setTimeout`, также срабатывает, но позже, уже после возникновения `unhandledrejection`, так что это ни на что не влияет.

## 8. `Async`, `await`
- Асинхронные функции:
    - `async` ставится перед функцией.
    - У слова async один простой смысл: эта функция всегда возвращает промис.
    - Значение других типов оборачиваются в завершившийся успешно промис автоматически.
    - Например:
        ```js
        async function f() {
            return 1
        }
        f().then(alert) // 1
        ```
- `Await`:
    - Работает только внутри `async-функций`.
        ```js
        let value = await promise
        ```
    - Заставляет интерпретатор `JS` ждать до тех пор, пока промис справа от `await` не выполнится.
    - После чего оно вернёт его результат, и выполнение кода продолжится.
    - Обратите внимание, хотя await и заставляет JS дожидаться выполнения промиса, это не отнимает ресурсов процессора.
    - Пока промис не выполнится, `JS-движок` может заниматься другими задачами: выполнять прочие скрипты, обрабатывать события и тп.
    - По сути, это просто синтаксический сахар для получения результата промиса, более наглядный, чем `promise.then`.
- `await` нельзя использовать в обычных функциях.
- Если да, то получим синатксическую ошибку.
- `await` нельзя использовать на верхнем уровне вложенности:
    - Нельзя использовать вне тела функции.
    - Можно обернуть код в анонимную async-функцию, тогда всё заработает.
- `await` работает с `thenable`-объектами:
    -Идея в том, что если у объекта можно вызвать метод `then`, этого достаточно, чтобы использовать его с `await`.
    - В примере ниже, экземпляры класса `Thenable` будут работать вместе с `await`:
        ```js
        class Thenable {
            constructor(num) {
                this.num = num
            }
            then(resolve, reject) {
                alert(resolve)
                setTimeout(() => resolve(this.num * 2), 1000)
            }
        }
        async function f() {
            let result = await new Thenable(1)
            alert(result)
        }
        f()
        ```
- Методы класса могут быть асинхронными.
- Обработка ошибок:
    - Когда промис завершается с ошибкой - будет выброшено исключение.
    - Как если бы на это месте находилось выражение `throw`.
    - Пример:
        ```js
        async function f() {
            await Promise.reject(new Error('Упс!'))
        }
        ```
    - Делает то же самое, что и такой:
        ```js
        async function f() {
            throw new Error('Упс!')
        }
        ```
    - Но есть отличие, промис может завершиться с ошибкой не сразу, а через некоторое время.
    - Такие ошибки можно ловить, используя `try..catch`, как с обычным `throw`.
        ```js
        async function f() {
            try {
                let response = await fetch('http://no-such-url)
            } catch (err) {
                alert(err) // TypeError: failed to fetch
            }
        }
        ```
    - Если у нас нет `try..catch`, асинхронная функция будет возвращать завершившийся с ошибкой промис.
    - В этом случае мы можем использовать метод `.catch` промиса, чтобы обработать ошибку.
    - `async/await` и `promse.then/catch`:
        - Для обработки ошибок лучше использовать блок `try/catch`.
        - Но в верхних уровнях нужно использовать метод .catch, если нет асинхронной функции.
    - `async/await` отлично работает с `Promise.all`.
